[build]
  command = "npm run build"             # Command to build your app
  publish = ".next"                      # Directory to publish after the build
  functions = "netlify/functions"        # Directory for serverless functions (optional)

[[plugins]]
  package = "@netlify/plugin-nextjs"    # Next.js adapter for Netlify

[build.environment]
  NODE_ENV = "production"                # Set environment to production

[cache]
  paths = ["node_modules/.prisma/client"] # Caching settings (optional)
